version: '3.1'
services:
 mongo:
  image: mongo
  #restart: always
  environment:
   MONGO_INITDB_ROOT_USERNAME: username
   MONGO_INITDB_ROOT_PASSWORD: password
  ports:
   - 27017:27017
  volumes:
   - db:/data/db
  networks:
   - network1


 app:
  build: .
  #restart: always
  ports:
   - 8080:8080
  networks:
   - network1


volumes:
  db:

networks:
 network1:
  driver: bridge
